---

- hosts: all
  become: true
  tasks:

  - name: update  repository index
    yum:
      update_cache: yes

  - name: remove apache2 package
    yum:
      name: httpd
      state: absent

  - name: stop and disable Apache service
    service:
      name: httpd
      state: stopped
      enabled: false
    ignore_errors: true
      

  - name: Remove PHP packages
    yum:
      name:
        - php
        - php-cli
        - php-common
        - php-mysqlnd
      state: absent
